SAP/ui5-inspector

README.md
@Chariyski I guess this is what you wanted to have. The current one is based on a Erlang project (https://hex.pm/packages/plug).
"https://img.shields.io/github/license/..." seems to be unresponsive atm, and as I guess the license won't change, this custom badge should be fine.
=> Correct license badge

app/scripts/injected/main.js, app/scripts/modules/ui/helpers/DataViewHelper.js, tests/modules/ui/helpers/DataViewHelper.spec.js
This fixes the case when you clear the value of a property which
resulted into setting it to "0".
Now "null" will be used which set the property to the default value.
However this might not be the expected result (e.g. when the default
value is a string, which makes it impossible to clear it).
A way to explicitly reset a property value might be a better solution.
=> [FIX] Change property to empty value

app/scripts/injected/main.js
After an error from setting a new value of a control property, the value should return back to the initial one.
=> [FIX] Update control property

app/vendor/ToolsAPI.js
Hi all,
this commit allows for the display of Data in an ODataModel as its getData function call the internal getProperty-method, that needs an internal path. 
By calling this with the root path ("/") the whole data-object get fetched.
=> [FIX] add support for ODataModel data display

app/scripts/injected/detectUI5.js, app/vendor/ToolsAPI.js
For NetWeaver ABAP hosted UI5 applications, the sap-ui-version.json does not include any "gav" (group artifact version) property. Which lead to some issues displaying the frameworks name and version.
The sap-ui-version.json in those cases actually looks like this:
```json
{
"name": "SAPUI5-on-ABAP",
"version": "1.30.1",
"buildTimestamp": "",
"scmRevision": "",
"libraries": [...]
}
```
---
I hereby offer a fix for the two issues I identified:
In the popup, the core version is not displayed (although it got detected correctly):
Because the ToolsAPI wasn't able to detect the frameworks name (as it was looking for the "gav" property) it returned an empty string. This lead to the version getting stored in the object poperty "<empty string>".
The popup however reads the version from either an …
=> [FIX] Display of UI5 version for ABAP hosted apps

app/scripts/modules/ui/DataView.js, app/scripts/modules/ui/helpers/DataViewHelper.js, app/styles/less/modules/DataView.less, tests/modules/ui/helpers/DataViewHelper.spec.js
The implementation for added typeinfo mixes currentElement and currentElement.data.
In `DVHelper._addKeyTypeInfo` is a check for `Array.isArray(element)`, which returns always false cause the provided element is an object with **options** - this is the condition in the DataView to get to the point where `DVHelper._addKeyTypeInfo` is called. Furthermore the functions checks the length of either the element itself or element.data dependent on the type, which is inconsistent.
With this fix it is possible to provide (nested) arrays that can be expanded/collapsed (if wanted). The array could contain sections (objects with an **options** entry) itself to enable more detailed nested views. If collapsed, the number of elements is shown. In case of an object, it will either show ellipsis if the …
=> [FIX] DataView: show correct type info (supporting arrays)

app/scripts/modules/ui/helpers/DataViewHelper.js, tests/modules/ui/helpers/DataViewHelper.spec.js
This commit fixes an issue that makes a parent section expandable if any child element is expandable.
Clicking in the yellow area collapses the whole section cause the homeIcon entry is marked as expandable...
... even though the main section itself is not marked as expandable (no arrow).
=> [FIX] DataView: toggleCollapse only if arrow tag is a direct child

app/scripts/modules/injected/controlUtils.js, tests/modules/ui/DataView.spec.js
Close 'clickable-value' tag was never added due missing parenthesis.
=> [FIX] ClickableValue: correct closing tag

.jscsrc, app/scripts/modules/injected/controlUtils.js, app/scripts/modules/ui/DataView.js, app/scripts/modules/ui/helpers/DataViewHelper.js, tests/modules/ui/DataView.spec.js
It would be helpful to have visual presentation of what other options are when it comes to control properties of UI5 enum types. In this change they are added as options in a select box and can be changed dynamically. It is gaining better user experience.
=> Editable value fields extended for properties of enum type

app/manifest.json
Problem:
The manifest contains a property name "persistence" that is not defined in the manifest file format specification: https://developer.chrome.com/docs/extensions/mv2/manifest/
Solution:
Corrected to the standard name "persistent" as defined in the manifest file format specification.
=> corrected field

app/vendor/ToolsAPI.js
Since the upcoming 1.100 version, the old check will no longer be valid.
=> fix: update check for version

app/scripts/injected/detectUI5.js, app/vendor/ToolsAPI.js
Problem: When the inspected app is built the UI5 Tooling, the version
which we take from the "sap.ui.getVersionInfo" API is incorrect.
This results in some unwanted behavior in the "Event Registry" tab of
the inspector.
Solution: We take the framework version from the framework's core
configuration which always returns the correct data.
=> fix: fixed UI5 version detection

app/scripts/background/main.js, app/scripts/devtools/panel/ui5/main.js
1) Remove invalid parameter passed to the utils.sendToAll function that called an "invalid signature" error from chrome
2) Ensured that the iframe URL is shown in the frames dropdown even the iframe has no UI5 content
=> fix: remove invalid parameter

app/html/panel/ui5/index.html, app/scripts/devtools/panel/ui5/main.js, app/scripts/modules/ui/OElementsRegistryMasterView.js, app/scripts/modules/ui/XMLDetailView.js, app/styles/less/modules/XMLView.less, app/styles/less/themes/base/base.less, app/vendor/ToolsAPI.js, tests/styles/themes/dark/dark.css, tests/styles/themes/light/light.css
This PR introduces a new feature for the `Elements Registry` for `sap.ui.core.mvc.XMLView` controls. It provides easy access to the definition of an XMLView. 
XMLViews may be bundled and minified in a component or library preload and therefor not easy to read. On top of that SAP Fiori elements is generating XMLViews dynamically based on OData metadata.
* Select the tab `Elements Registry`
* Search and / filter for `XMLView` or `sap.ui.core.mvc.XMLView`
* Select any control of that type
* Select the tab `XML View` in the details area
The XML of the selected XMLView will be shown.
=> feat: show XML of XMLViews in elements registry

app/scripts/modules/ui/ControlTree.js
Problem: Error from querySelector when called with element id that contains special characters. 
Sample: https://jsbin.com/suhovumigu/1/edit?html,js,output shows that querySelector throws error when called with id string that contains "::", as used in many apps
Solution: applied the recommended selector format
=> fix: allow selection of element by id with special chars

app/scripts/modules/content/highLighter.js
Fixes https://github.com/SAP/ui5-inspector/issues/212
Findings:
When the DevTools is closed and reopened, the content script containing the highlighter is reloaded 
=> the value of _hightlighter global var is overwritten
=> the code in the setDimension function that accesses the _hightlighter by closure cannot find the reference anymore
Solution:
Made the highlighter Singleton and defined _hightlighter as a private field of its single object, to allow referencing it by this._highlighter, rather than closure
=> fix: highlighter error

app/scripts/devtools/panel/ui5/main.js, app/scripts/injected/main.js, app/scripts/modules/injected/controlUtils.js, app/scripts/modules/ui/DataView.js, app/styles/less/modules/DataView.less, tests/styles/themes/dark/dark.css, tests/styles/themes/light/light.css
_The feature is Inspired by the `Store ... as global variable` feature of the chrome dev. tools debugger._
A click on the id of a control in the `Properties` tab of the `Control Inspector` as well as of the `Elements Registry` or on the button `Copy to console` in the `Action` tab  of the `Control Inspector` will create a global variable starting with 'ui5$' and a number e.g. 'ui5$0' that refers to this control. All control references will be collected in the variable `ui5$temp` for convenience.
The control is not directly assigned to the global variable but wrapped in an object showing the class of the control in the property `isA`. The actual control is in the property `control`. 
The `savedAs` property is helpful when looking at all collected globals in `ui5$temp`.
The feature is …
=> feat: copy control to console

app/scripts/devtools/panel/ui5/main.js, app/scripts/modules/injected/controlUtils.js, app/scripts/modules/ui/DataView.js, app/styles/less/modules/DataView.less
--Extend the "copy control to console" functionality to cover all data-view panels that show the control-id in their titles
--Minor refactoring to unify the event handling of all elements that trigger the "copy control to console" action
=> feat: extend copy control to console

app/vendor/ToolsAPI.js
Improved handling of OData V4 models
Fixes https://github.com/SAP/ui5-inspector/issues/81
=> fix: display odata v4 binding context properly

app/scripts/content/main.js
Fixes duplicate action execution the following scenario:
1. Select a control from the control tree and execute an action e.g. 'copy control to console'
2. Close and reopen the DevTools, while staying on the same page and URL (no navigation)
3. Repeat step 1
Expected: the same result as received for step 1
Actual: the result is displayed twice (e.g. control is copied to the console twice)
On inspection we see that the content script "content/main.js" is injected each time the devTools is reopened.
This happens on request from the script behind the UI5-Inspector tab in DevTools because that script is also
re-executed whenever the DevTools panel is opened and it does not keep any state that persists between the multiple
close and reopen of the panel.
Fixed by adding a flag to the window …
=> fix: prevent duplicate output

app/vendor/ToolsAPI.js
There is an inconsistent deprecations in ToolsAPI. _getFrameworkInformation.
ToolsAPI.js is using the deprecated methods jQuery.sap.debug and jQuery.sap.statistics.
=> fix: replaced inconsistent deprecations

app/vendor/ToolsAPI.js
Fixes: https://github.com/SAP/ui5-inspector/issues/250
=> fix: console error

app/scripts/background/main.js
Issue:
Empty popup upon pressing the pageAction, due to error in processing its request to inject content script into the page [that obtains more information about the page]. 
The error is thrown because the request does not contain "frameId", so it passed to chrome.scripting.executeScript a "frameId" with the invalid value of "undefined"
Solution:
The page action should be showing information about the main frame. Given that scripting.executeScript selects the main frame by default, only ensure that no "frameId" with the invalid value of "undefined" is passed to it
=> fix: error from popup
